# Chat welcome message settings
chat:
  enabled: true
  # Show welcome message for full joins (not transfers from other servers)
  full-joins-only: true
  # Message lines
  message:
    - "<gray>------------------------------------"
    - ""
    - "<green>Welcome to the server, {player}!"
    - "<yellow>We hope you enjoy your stay!"
    - "<blue>Type /help for assistance."
    # You can use all MiniMessage features like click and hover actions
    - "<click:open_url:https://example.com><hover:show_text:'Click to visit our website'>Visit our website!</hover></click>"
    - ""
    - "<gray>------------------------------------"

# Title welcome message settings
title:
  enabled: true
  # Show title for full joins only
  full-joins-only: true
  # Main title text
  title: "<gold><bold>Welcome!</bold></gold>"
  # Subtitle text
  subtitle: "<gray>Enjoy your stay, {player}!</gray>"
  # Title display timings (in seconds)
  fade-in: 1.0
  stay: 2.0
  fade-out: 1.0

# Sound welcome message settings
sound:
  enabled: true
  # Show sound for full joins only
  full-joins-only: true
  # Sound to play (Bukkit Sound enum name - see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html)
  sound: "ENTITY_PLAYER_LEVELUP"

# Global settings
settings:
  # Debug mode for troubleshooting
  debug: false
