name: GoxyWelcome
version: "${version}"
main: com.github.iipanda.goxywelcome.GoxyWelcome
api-version: "1.18"
depend: [goxy]
softdepend: [PlaceholderAPI]
commands:
  goxywelcome:
    description: GoxyWelcome plugin commands
    usage: /goxywelcome <reload>
    permission: goxywelcome.admin
permissions:
  goxywelcome.admin:
    description: Access to GoxyWelcome admin commands
    default: op
